apiVersion: batch/v1
kind: CronJob
metadata:
  name: trigger-check
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl
            image: curlimages/curl:7.82.0
            command:
            - /bin/sh
            - -c
            - |
              curl -X POST \
                -H "Content-Type: application/json" \
                -d '{
                  "repo-revision": "main"
                }' \
                el-check-and-trigger-build-listener.default.svc.cluster.local:8080
          restartPolicy: Never