apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: monorepo-pipeline-run-
spec:
  pipelineRef:
    name: build-monorepo-apps
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: my-secret-ws
      secret:
        secretName: my-secret
  params:
  - name: repo-revision
    value: main