apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todosvc
spec:
  destination:
    name: ''
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://andrescosta.github.io/todo-charts
    targetRevision: '>=0.4.0' 
    chart: todo-svc-jobico
  syncPolicy:
    automated: {}
  sources: []
  project: default
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todoweb
spec:
  destination:
    name: ''
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://andrescosta.github.io/todo-charts
    targetRevision: '>=0.4.0' 
    chart: todo-web-jobico
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
