apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todosvc
spec:
  destination:
    name: ''
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://andrescosta.github.io/todo-charts
    targetRevision: '*' 
    chart: todo-svc-jobico
  sources: []
  project: default
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todoweb
spec:
  destination:
    name: ''
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://andrescosta.github.io/todo-charts
    targetRevision: '*'
    chart: todo-web-jobico
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
