apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: svc-builder-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-builder-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 1Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: svc-builder 
spec:
  template:
    spec:
      imagePullSecrets:
        - name: reg-cred-secret
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      initContainers:
        - name: init-svc
          image: reg.jobico.local/buildah 
          command: 
          - /script/build.sh  
          - init
          - --repository=https://github.com/andrescosta/todo-jobico-cloud
          - --branch=argocd-helm
          - --build-dir=todo-svc/
          - --registry=reg.jobico.local
          - --image-name=todosvc
          - --current-version=1.1
          - --work-dir=/repo
          - --helm-repository=https://oauth2:{token}@github.com/andrescosta/todo-charts
          - --helm-branch=main
          - --helm-chart=todo-svc-jobico
          - --helm-version=0.4
          - --git-user=builder
          - --git-email=builder@git
          - --frequency=30
          - --token-file=/token/token_git_hub.private
          - --first-build
          - --verbose
          volumeMounts:
          - name: builder-vol
            mountPath: "/repo"
          - name: script
            mountPath: "/script"
          - name: github-token
            mountPath: /token
      containers:
        - name: svc-builder 
          image: reg.jobico.local/buildah 
          securityContext:
            privileged: true
          command: 
          - /repo/todo-svc-jobico.sh  
          volumeMounts:
            - name: script
              mountPath: "/script"
            - name: builder-vol
              mountPath: "/repo"
            - name: ca
              mountPath: "/etc/containers/certs.d/reg.jobico.local"
            - name: github-token
              mountPath: /token
      volumes:
        - name: script
          configMap:
            name: build-map 
            defaultMode: 0050
        - name: builder-vol
          persistentVolumeClaim:
            claimName: svc-builder-pvc
        - name: ca 
          configMap:
            name: kube-root-ca.crt 
        - name: github-token
          secret:
            secretName: github-token
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: web-builder 
spec:
  template:
    spec:
      imagePullSecrets:
        - name: reg-cred-secret
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      initContainers:
        - name: init-web
          image: reg.jobico.local/buildah 
          command: 
          - /script/build.sh
          - init
          - --repository=https://github.com/andrescosta/todo-jobico-cloud
          - --branch=argocd-helm
          - --build-dir=todo-web/
          - --registry=reg.jobico.local
          - --image-name=todoweb
          - --current-version=1.1
          - --work-dir=/repo
          - --helm-repository=https://oauth2:{token}@github.com/andrescosta/todo-charts
          - --helm-branch=main
          - --helm-chart=todo-web-jobico
          - --helm-version=0.4
          - --git-user=builder
          - --git-email=builder@git
          - --frequency=30
          - --token-file=/token/token_git_hub.private
          - --first-build
          - --verbose
          volumeMounts:
            - name: script
              mountPath: "/script"
            - name: builder-vol
              mountPath: "/repo"
            - name: github-token
              mountPath: /token
      containers:
        - name: web-builder 
          image: reg.jobico.local/buildah 
          securityContext:
            privileged: true
          command: 
          - /repo/todo-web-jobico.sh  
          volumeMounts:
            - name: script
              mountPath: "/script"
            - name: builder-vol
              mountPath: "/repo"
            - name: ca
              mountPath: "/etc/containers/certs.d/reg.jobico.local"
            - name: github-token
              mountPath: /token
      volumes:
        - name: script
          configMap:
            name: build-map 
            defaultMode: 0050
        - name: builder-vol
          persistentVolumeClaim:
            claimName: web-builder-pvc
        - name: ca 
          configMap:
            name: kube-root-ca.crt 
        - name: github-token
          secret:
            secretName: github-token
      restartPolicy: Never