apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: obs-todosvc
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: todosvc
  podMetricsEndpoints:
  - port: svc
    path: /actuator/prometheus
    scheme: http
    interval: 15s
