apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: todosvc
  name: todosvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todosvc
  template:
    metadata:
      labels:
        app: todosvc
      annotations:
        jobico-ver: "{version}"
    spec:
      imagePullSecrets:
        - name: reg-cred-secret
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: devk8s
            - name: PYROSCOPE_AGENT_ENABLED
              value: "false"
          image: reg.jobico.org/todosvc:latest
          imagePullPolicy: Always
          name: todosvc
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
              name: svc
      restartPolicy: Always