apiVersion: v1
kind: Service
metadata:
  labels:
    app: todosvc
  name: todosvc
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: todosvc
  type: LoadBalancer