---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: monorepo-pipeline-template
spec:
  params:
    - name: repo-url
      description: The git repository URL to clone from.
    - name: repo-revision
      description: The git revision to checkout.
    - name: resources
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: monorepo-pipeline-run-
      spec:
        pipelineRef:
          name: build-monorepo-apps
        workspaces:
          - name: shared-workspace
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
          - name: my-secret-ws
            secret:
              secretName: my-secret
        params:
          - name: repo-url
            value: $(tt.params.repo-url)
          - name: repo-revision
            value: $(tt.params.repo-revision)
          - name: resources
            value: $(tt.params.resources)

---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: monorepo-pipeline-binding
spec:
  params:
    - name: repo-url
      value: $(body.repo-url)
    - name: repo-revision
      value: $(body.repo-revision)
    - name: resources 
      value: $(body.resources)
---
apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: monorepo-pipeline-trigger
spec:
  bindings:
    - ref: monorepo-pipeline-binding
  template:
    ref: monorepo-pipeline-template
---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: monorepo-pipeline-listener
spec:
  triggers:
    - triggerRef: monorepo-pipeline-trigger

  serviceAccountName: tekton-sa