apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-monorepo-apps
spec:
  workspaces:
    - name: shared-workspace
    - name: my-secret-ws
  params:
    - name: repo-revision
      type: string
      description: The git revision to checkout.
  tasks:
    - name: fetch-repo
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: https://github.com/andrescosta/todo-jobico-cloud
        - name: revision
          value: $(params.repo-revision)
    - name: build-image-todosvc
      taskRef:
        name: buildah
      runAfter:
        - fetch-repo
      params:
      - name: CONTEXT
        value: todo-svc
      - name: DOCKERFILE
        value: todo-svc/Dockerfile
      - name: IMAGE
        value: reg.jobico.org/todo-svc
      - name: TLSVERIFY
        value: false
      workspaces:
        - name: source  
          workspace: shared-workspace
        - name: dockerconfig
          workspace: my-secret-ws
    - name: build-image-todoweb
      taskRef:
        name: buildah
      runAfter:
        - fetch-repo
      params:
      - name: CONTEXT
        value: todo-web
      - name: DOCKERFILE
        value: todo-web/Dockerfile
      - name: IMAGE
        value: reg.jobico.org/todo-web
      - name: TLSVERIFY
        value: false
      workspaces:
        - name: source  
          workspace: shared-workspace
        - name: dockerconfig
          workspace: my-secret-ws