  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: commit-hash-cm
  data: {hash:""}
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build
spec:
  workspaces:
    - name: shared-workspace
    - name: buildah-secret-ws
  params:
    - name: repo-revision
      type: string
      default: main
      description: The git revision to checkout.
    - name: repo-revision-helm
      type: string
      default: main
      description: The git helm revision to checkout.
  tasks:
    - name: check-git
      taskSpec:
        params:
          - name: repo-revision
            type: string
            default: main
            description: The git revision to checkout.
        results:
          - name: git-hash
        steps:
          - name: get-remote-hash
            image: tfgco/kubectl
            script: |
              #!/bin/sh
              last_hash=$(git ls-remote https://github.com/andrescosta/todo-jobico-cloud $(params.repo-revision) | awk '{sub(/[ \t]+$/, "", $1); print $1}')
              current_hash=$(kubectl get configmap commit-hash-cm -o jsonpath='{.data.hash}')
              if [ "$current_hash" != "$last_hash" ]; then
                kubectl patch configmap commit-hash-cm -p "{\"data\":{\"hash\":\"$last_hash\"}}"
                printf "%s" "${last_hash}" > "$(results.git-hash.path)"
              else
                printf "" > "$(results.git-hash.path)"
              fi
    - name: fetch-repo
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      runAfter:
        - check-git
      when:
        - input: "$(tasks.check-git.results.git-hash)"
          operator: notin
          values: [""]
      params:
        - name: url
          value: https://github.com/andrescosta/todo-jobico-cloud
        - name: revision
          value: "$(tasks.check-git.results.git-hash)"
        - name: subdirectory
          value: app
    - name: fetch-repo-helm
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      runAfter:
        - check-git
      when:
        - input: "$(tasks.check-git.results.git-hash)"
          operator: notin
          values: [""]
      params:
        - name: url
          value: https://github.com/andrescosta/todo-charts
        - name: revision
          value: $(params.repo-revision-helm)
        - name: subdirectory
          value: helm
    - name: build-image-todosvc
      taskRef:
        name: buildah
      runAfter:
        - fetch-repo
      when:
        - input: "$(tasks.check-git.results.git-hash)"
          operator: notin
          values: [""]
      params:
      - name: CONTEXT
        value: app/todo-svc
      - name: DOCKERFILE
        value: app/todo-svc/Dockerfile
      - name: IMAGE
        value: reg.jobico.org/todosvc:$(tasks.check-git.results.git-hash)
      - name: TLSVERIFY
        value: "false"
      workspaces:
        - name: source  
          workspace: shared-workspace
        - name: dockerconfig
          workspace: buildah-secret-ws
    - name: build-image-todoweb
      taskRef:
        name: buildah
      runAfter:
        - fetch-repo
      when:
        - input: "$(tasks.check-git.results.git-hash)"
          operator: notin
          values: [""]
      params:
      - name: CONTEXT
        value: app/todo-web
      - name: DOCKERFILE
        value: app/todo-web/Dockerfile
      - name: IMAGE
        value: reg.jobico.org/todoweb:$(tasks.check-git.results.git-hash)
      - name: TLSVERIFY
        value: "false"
      workspaces:
        - name: source  
          workspace: shared-workspace
        - name: dockerconfig
          workspace: buildah-secret-ws
    - name: deploy-todo-svc
      taskRef: 
        name: helm-upgrade-from-source
      when:
        - input: "$(tasks.check-git.results.git-hash)"
          operator: notin
          values: [""]
      params:
      - name: charts_dir
        value: helm/charts/todo-svc-jobico
      - name: releases_version
        value: v1.0.0
      - name: release_name
        value: todo-svc
      - name: overwrite_values
        value: "image.tag=$(tasks.check-git.results.git-hash)"
      runAfter:
        - build-image-todosvc
      workspaces:
        - name: source  
          workspace: shared-workspace
    - name: deploy-todo-web
      taskRef: 
        name: helm-upgrade-from-source
      when:
        - input: "$(tasks.check-git.results.git-hash)"
          operator: notin
          values: [""]
      runAfter:
        - build-image-todoweb
        - deploy-todo-svc
      params:
      - name: charts_dir
        value: helm/charts/todo-web-jobico
      - name: releases_version
        value: v1.0.0
      - name: release_name
        value: todo-web
      - name: overwrite_values
        value: "image.tag=$(tasks.check-git.results.git-hash)"
      workspaces:
        - name: source  
          workspace: shared-workspace