apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-monorepo-apps
spec:
  workspaces:
    - name: shared-workspace
    - name: my-secret-ws
  params:
    - name: repo-url
      type: string
      description: The git repository URL to clone from.
    - name: repo-revision
      type: string
      description: The git revision to checkout.
    - name: java-app-dir
      type: string
      description: The directory containing the Java application.
    - name: react-app-dir
      type: string
      description: The directory containing the React application.
    - name: java-image-name
      type: string
      description: Name for the Java application image
    - name: react-image-name
      type: string
      description: Name for the React application image
  tasks:
    - name: fetch-repo
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.repo-revision)

    - name: build-java-image
      taskRef:
        name: buildah
      runAfter:
        - fetch-repo
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: dockerconfig
          workspace: my-secret-ws
      params:
        - name: CONTEXT
          value: $(params.java-app-dir)
        - name: DOCKERFILE
          value: $(params.java-app-dir)/Dockerfile
        - name: IMAGE
          value: $(params.java-image-name)
        - name: TLSVERIFY
          value: false

    - name: build-react-image
      taskRef:
        name: buildah
      runAfter:
        - fetch-repo
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: dockerconfig
          workspace: my-secret-ws
      params:
        - name: CONTEXT
          value: $(params.react-app-dir)
        - name: DOCKERFILE
          value: $(params.react-app-dir)/Dockerfile
        - name: IMAGE
          value: $(params.react-image-name)
        - name: TLSVERIFY
          value: false
